// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/logs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogCollector_CollectBatch_FullMethodName = "/cloudmesh.logs.v1.LogCollector/CollectBatch"
	LogCollector_StreamLogs_FullMethodName   = "/cloudmesh.logs.v1.LogCollector/StreamLogs"
)

// LogCollectorClient is the client API for LogCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RPC surface exposed by log-collector
type LogCollectorClient interface {
	// Primary: send a batch, receive a receipt (unary RPC)
	CollectBatch(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*CollectResponse, error)
	// High-throughput: client-side streaming for continuous ingestion
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEvent, CollectResponse], error)
}

type logCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewLogCollectorClient(cc grpc.ClientConnInterface) LogCollectorClient {
	return &logCollectorClient{cc}
}

func (c *logCollectorClient) CollectBatch(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*CollectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectResponse)
	err := c.cc.Invoke(ctx, LogCollector_CollectBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logCollectorClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEvent, CollectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogCollector_ServiceDesc.Streams[0], LogCollector_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEvent, CollectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogCollector_StreamLogsClient = grpc.ClientStreamingClient[LogEvent, CollectResponse]

// LogCollectorServer is the server API for LogCollector service.
// All implementations must embed UnimplementedLogCollectorServer
// for forward compatibility.
//
// RPC surface exposed by log-collector
type LogCollectorServer interface {
	// Primary: send a batch, receive a receipt (unary RPC)
	CollectBatch(context.Context, *LogBatch) (*CollectResponse, error)
	// High-throughput: client-side streaming for continuous ingestion
	StreamLogs(grpc.ClientStreamingServer[LogEvent, CollectResponse]) error
	mustEmbedUnimplementedLogCollectorServer()
}

// UnimplementedLogCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogCollectorServer struct{}

func (UnimplementedLogCollectorServer) CollectBatch(context.Context, *LogBatch) (*CollectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectBatch not implemented")
}
func (UnimplementedLogCollectorServer) StreamLogs(grpc.ClientStreamingServer[LogEvent, CollectResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLogCollectorServer) mustEmbedUnimplementedLogCollectorServer() {}
func (UnimplementedLogCollectorServer) testEmbeddedByValue()                      {}

// UnsafeLogCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogCollectorServer will
// result in compilation errors.
type UnsafeLogCollectorServer interface {
	mustEmbedUnimplementedLogCollectorServer()
}

func RegisterLogCollectorServer(s grpc.ServiceRegistrar, srv LogCollectorServer) {
	// If the following call panics, it indicates UnimplementedLogCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogCollector_ServiceDesc, srv)
}

func _LogCollector_CollectBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogCollectorServer).CollectBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogCollector_CollectBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogCollectorServer).CollectBatch(ctx, req.(*LogBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogCollector_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogCollectorServer).StreamLogs(&grpc.GenericServerStream[LogEvent, CollectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogCollector_StreamLogsServer = grpc.ClientStreamingServer[LogEvent, CollectResponse]

// LogCollector_ServiceDesc is the grpc.ServiceDesc for LogCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudmesh.logs.v1.LogCollector",
	HandlerType: (*LogCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectBatch",
			Handler:    _LogCollector_CollectBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _LogCollector_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/logs.proto",
}
